######################################################################
# Automatically generated by qmake (2.01a) mar. 24. mai 01:06:22 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += PPEnvironment.h PPObject.h PPWidget.h
SOURCES += main.cpp PPEnvironment.cpp PPWidget.cpp
